[GSoD] Resume/suspend troubleshooting
QubesOS/qubes-doc pull request #1053
Opened 2020-10-10 08:54 UTC by PROTechThor

I renamed "Wireless Troubleshooting" to "Suspend/Resume Troubleshooting" and added more content to it.

2020-10-10 12:58 UTC, marmarek approved these changes

2020-10-11 03:00 UTC, andrewdavidwong commented
@PROTechThor: FYI, if you notice a failing Travis CI check, you can click "Details," then "View more details on Travis CI" at the bottom, then scroll all the way to the bottom of the (long) log, and it will show you what caused the failures. (I don't know why they make it so hard to find.) In this case, the relevant portion is:

```
The following new unknown spellings were introduced:
    +hyperthreading
    +wirele
In addition, the following suspicious spellings were eliminated:
    -suspendi
The introduced suspects in context are:
./_doc/user/troubleshooting/resume-suspend-troubleshooting.md:124:To solve the problem, disable hyperthreading in the BIOS. This [external guide](https://www.pcmag.com/news/how-to-disable-hyperthreading) explains how to disable hyperthreading. 
./_doc/user/troubleshooting/resume-suspend-troubleshooting.md:125:Since Qubes does disable hyperthreading by default (by not using secondary threads), you won't pay any performance cost.
+all_ok=false
+echo
+htmlproofer ./_site --disable-external --checks-to-ignore ImageCheck --file-ignore ./_site/video-tours/index.html --only_4xx --url-ignore /qubes-issues/
Running ["ScriptCheck", "LinkCheck"] on ["./_site"] on *.html... 
Ran on 1006 files!
- ./_site/doc/index.html
  *  internally linking to /doc/installation-troubleshooting/, which does not exist (line 331)
     <a href="/doc/installation-troubleshooting/">Installation Troubleshooting</a>
htmlproofer 3.16.0 | Error:  HTML-Proofer found 1 failure!
```

I can't find the instance of `wirele`, so I'm not sure what to make of that. `hyperthreading` is ok, but technically it should be [`hyper-threading`](https://en.wikipedia.org/wiki/Hyper-threading). The real problem is the broken link. Would you mind fixing that up before we merge this?

2020-10-11 03:45 UTC, PROTechThor commented
> I can't find the instance of `wirele`, so I'm not sure what to make of that. `hyperthreading` is ok, but technically it should be [`hyper-threading`](https://en.wikipedia.org/wiki/Hyper-threading). The real problem is the broken link. Would you mind fixing that up before we merge this?

@andrewdavidwong 
All fixed! Thanks for mentioning. I did see the broken link, but I assumed the Installation Troubleshooting will be merged before this, and the link will eventually exist :D

2020-10-11 04:08 UTC, andrewdavidwong commented
> All fixed! Thanks for mentioning. I did see the broken link, but I assumed the Installation Troubleshooting will be merged before this, and the link will eventually exist :D

Ohh, I see. As Marek mentioned, we usually try to keep PRs independent of each other so that they can be merged in any order, or at least so that merging one doesn't cause any problems (e.g. merge conflicts) in others.

However, since you've already got all these PRs open, I would be happy to merge them in whichever order would make things easiest for you. Would that just be the order in which they were opened?

2020-10-11 04:17 UTC, PROTechThor commented
> However, since you've already got all these PRs open, I would be happy to merge them in whichever order would make things easiest for you. Would that just be the order in which they were opened?

Yes, in that order. If any conflicts arise, I'll resolve them somehow.

2020-10-13 02:37 UTC, andrewdavidwong commented
@PROTechThor, ready for you to resolve merge conflicts on this one now.

2020-10-14 06:55 UTC, PROTechThor commented
@andrewdavidwong

2020-10-15 07:45 UTC, PROTechThor commented
@marmarek 
Can you please review my latest commit?

2020-10-16 15:12 UTC, marmarek requested changes

2020-10-16 15:12 UTC, marmarek commented on user/troubleshooting/resume-suspend-troubleshooting.md
> +This can be achieved under a Windows HVM by opening the Device Manager, selecting the actual device (such as a USB controller), 'Disabling' the device, and then 'Enabling' the device again.
Since this solution is specific to Windows, add "Windows HVM" to the section header.

2020-10-18 04:26 UTC, marmarek approved these changes

2020-10-19 00:22 UTC, merged