[GSoD] Disk Troubleshooting
QubesOS/qubes-doc pull request #1059
Opened 2020-10-18 06:27 UTC by PROTechThor

2020-10-18 06:31 UTC, PROTechThor commented
This page covers content from https://www.qubes-os.org/doc/out-of-memory/ and @clayt0nk pull request #1043 . 
Also see this discussion: https://groups.google.com/g/qubes-users/c/TlCoT1jrVVY

2020-10-18 18:11 UTC, marmarek requested changes
Added some comments to bring the content up to date for Qubes 4.0 (some of it is from 3.2 or older times).

2020-10-18 18:11 UTC, marmarek commented on user/troubleshooting/disk-troubleshooting.md
> +4.  Remove some unneeded files in dom0 home (if you have any, most likely not).
It may make sense to look into `/var/log` in dom0, and also `/var/log/qubes`.

2020-10-18 18:11 UTC, marmarek commented on user/troubleshooting/disk-troubleshooting.md
> +    sudo xl console -t pv sys-usb
better `qvm-console-dispvm sys-usb`

2020-10-19 14:22 UTC, PROTechThor commented on user/troubleshooting/disk-troubleshooting.md
> +The default private storage max size is 2 GB, but it's very easy to increase as needed.
@marmarek Are you suggesting I change the heading to something else? If yes, what do you propose?

2020-10-21 02:00 UTC, marmarek commented on user/troubleshooting/disk-troubleshooting.md
> +The default private storage max size is 2 GB, but it's very easy to increase as needed.
I would remove those two sentences from here. If we'd get some steps relevant to in-VM disk space issues, then they would fit there.

2020-10-24 11:13 UTC, marmarek approved these changes
-----BEGIN PGP SIGNED MESSAGE-----Hash: SHA256Approved as of f28b6b46059c6a0bf7e3acc9055f60b13a5a3c27-----BEGIN PGP SIGNATURE-----iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAl+UDGwACgkQ8yiUvpaEk4oiFBAAqcZAT+3WMh9aRx3vQlo7n1Y0QmC1oGT09/6lVcxXJuhKH2QbYS9S23TL1j6s04/8AOkwdjFoAguRfYEIhUMdMF8G3TFv62BLFKXcWq/rrzXrXogEQNaXmRYapuRDGec3Fv6jMhhbvPwOX+ABNdSJ6Yjs1zI4jFwd7nvH2kZjCNjMkfDA6TkXNoiDuy72089ORWQyVkGmlMoN2tV+n08boVlj+CuwU1w1ZPLGboYYsY5699DviPA7nyrvfy+Ann+WNgm0Lbozr2Td7YOKXiMzf0sSu1brAm/DEoE2EiCOhkBQ2qR7vMM7xdNm+Uzq4UjgKepsIcLtv9wz4v22134bZluZOqrMq9SuLP6Gt3ZpSh0gPDr6v647YK66P1OXgDILkMtc8qAX+1Ge17cS4EdzmZ1u5HQ98bXuUVfTNCeywLJJV5gLUGVyC0jq7WW1T+eVbDt5tXh88XQASrOrlOiRqzOxhX22Ms3FNi4zcq4YlLToDQGmZNPIWBktf8JDfsmP5cX67XkKeydW0HfbRWRSOlKJoCJ7QOn3UEsrHxbQyg93al+YtUouWEP/jm426oZM+uR1VnOZZiUR87BvMaln42WNftvEgX9Uyx5fJES5xwZth9P3qw2dBZ4mP4b3O0Axy8fk977rZD0wgUIjP69p5Oqoh7rZqS+Ogt9sEQha0A0==FyVL-----END PGP SIGNATURE-----

2020-10-24 11:14 UTC, marmarek approved these changes
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Approved as of f28b6b46059c6a0bf7e3acc9055f60b13a5a3c27
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAl+UDLIACgkQ8yiUvpaE
k4r6ZQ//d4RVj1RtZmxY9h4hiNzIDJmY2Lh9t88/jeOGtVdb+iA4lJuK7o+pDWyi
1rTSp9moWt5eN5kMY3f286ifgQN7+1dFP0Wvo8s8bR7g7uZM00VSF/kexykqkVPp
CJjm5NB17UPJVTyCdAr7I6/684q5dLtMVPjc1XrIF+6nhnfHvyO+71jRePNx2YyP
c7zEth4JhIjiIjrSCw0IO3MRbvQviuoKeGxirKOC2rtWSMd7OqNHjW6lTMKb/O+a
enYnHTxqlILZF+ZVE/oKiG6w6Zy/x3DUS9INNJ8szS0pTAaZrQixiFv/CrM8cBeS
Ol14lUWgN/OZ5SWGi4BRPrmCC2iTZfMafkPuTJ+hUhZl/Q6I7KAy48vyrU3n1gYS
ZqgDqdaPd1/ON5AXwFNpP9+iF+LEr7AxPmkXWtCdi+pOywaMcy5pSdQ2I7sLzrMP
OxZoiG/nRn02vHPgJ5+eWAwQCiopfkxqu7N/BNyb+lWyoZu9j9fXRrv7ZVC2zN0/
8JH59glT2eAbYEiPoiw/P/5nw1mDZPjOnrTEAszv/jY3KzFA4BVEZ3EArTIDF/QP
l/DK1neh/rzWcTxuv2bZ9Xu98xfRJ1cCVPZKyxvZJw/z1SJFKlNQsq2DOxnFbuPg
S0HRUkw0elj09itR5g1B+O4K0SegifeuAiRsypwQqht/yviexc0=
=mOda
-----END PGP SIGNATURE-----

2020-10-24 11:17 UTC, marmarek approved these changes
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Approved as of f28b6b46059c6a0bf7e3acc9055f60b13a5a3c27
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAl+UDUAACgkQ8yiUvpaE
k4pt5g//SAd3fQNMlI1Xt74WU/KMMmtljoqtY/b8j9PSEE1/xWq0IyZlezqV2GwT
GK8ioUb//FYNzLnQisNFRDSaZPBkJsZ/Viq8SRXNaSwTyzCHlL5klqbH6T65SWUu
q9N6P/Xf4OPNYjzqDdofjh/12qu583BN3SiNl3SRUUnrRG+w5neNtyhQwXBOKVje
LfhJvD9cS0DFgCK89Of6EvXux9E3HK8v8cN4g+yMJAcPUrIirOfhIJm88ACwFldc
5HYNPT4lOsKKm9cSSgUy9Cf7nAppQTC86mGBcTDJBlXNC90Tequt2qj748K3x2lR
KKv2KYmum81PC4n/kFKkGduVtL6hSZ+pKumwdCBLBMZe6xzVVepUjiWsY3OgvMmx
1YhQJOOJgVw15pSVr48NCVngGEcUxgf4nvDM5IKgKFq9JUzCEIt/7hqbEFQ1Zq5e
wzcmEB34dqr8Zyk9UVOOvTHiuSjRCmtvFtKgSiqRn8ryw7adx6pLnsjtiIYjzlN4
+vddrb8w2IKW+pTRhNnjbR9DovoSKFMFPkTfC1qNvd/SDbXGFuCDmtCf8D/JAsaW
bJZWz2BLqLpcrXjd7vXPJpJ5HtfiOqniY3jsPzofgQ6IN2O7MT14H2P/H7h2UQdC
rHEE3Yj6Cgq9qcS7U+UqsTWHLLiJuY9OgzwwSgDLFUmFmcMK5vs=
=FdIc
-----END PGP SIGNATURE-----
```

2020-10-24 11:25 UTC, merged