[GSoD] PCI Troubleshooting
QubesOS/qubes-doc pull request #1060
Opened 2020-10-18 09:11 UTC by PROTechThor

It appears there will be no "Wireless Troubleshooting" guide, since everything related to that falls this PCI Troubleshooting. Which is fine, since the previous Wireless Troubleshooting has been redirected to Suspend/Resume.

2020-10-18 09:42 UTC, PROTechThor commented
## Sources and discussions 
### The _DMA Errors_ and _PCI Passthrough Issues_ sections were migrated from [PCI Devices](https://www.qubes-os.org/doc/pci-devices/#possible-issues) doc. 

### "Unable to reset PCI device" errors  
 **libvirt.libvirtError: internal error: Unable to reset PCI device**
- https://github.com/QubesOS/qubes-issues/issues/1393  
- https://www.reddit.com/r/Qubes/comments/apkwwo/on_qubes_setup_got_this_error/ 
- https://groups.google.com/g/qubes-users/c/CCPXkGYHzaY
- https://groups.google.com/g/qubes-users/c/o8eahbAg3q0/m/v1Ztl8aU-UkJ
**internal error: Unable to reset PCI device [...]: no FLR, PM reset or bus reset available**

- https://www.reddit.com/r/Qubes/comments/9absfm/manually_creating_usb_qube_returns_an_error/ 
- https://github.com/QubesOS/qubes-issues/issues/4853
- https://www.qubes-os.org/faq/#i-created-a-usbvm-and-assigned-usb-controllers-to-it-now-the-usbvm-wont-boot
- https://www.reddit.com/r/Qubes/comments/c7dbe6/sysnet_cant_start/

### Broadcom BCM43602 Wi-Fi card causes system freeze

- https://groups.google.com/g/qubes-users/c/rH2PCdtkp8A

### Wireless card stops working after dom0 update 

- https://www.reddit.com/r/Qubes/comments/fhpma0/sysnet_wont_connect_to_the_internet/
- https://groups.google.com/g/qubes-users/c/BDWbrLegik0/m/z0jSKW1RAwAJ
- https://www.reddit.com/r/Qubes/comments/fh5w7f/qubes_403_dom0_update_kills_my_wifi_device/

2020-10-18 18:21 UTC, marmarek requested changes

2020-10-18 18:21 UTC, marmarek commented on user/troubleshooting/pci-troubleshooting.md
> +    # qvm-prefs -s netvm kernelopts "iommu=soft swiotlb=8192"
While this may be needed for some devices in some form, the 8192 value is the default already (some devices may require larger one).

2020-10-21 01:57 UTC, marmarek approved these changes

2020-10-24 21:20 UTC, andrewdavidwong commented
@PROTechThor, it looks like this is the next GSoD PR in the list, but these need to be fixed before it can be merged::

```
- ./_site/doc/disposablevm-customization/index.html
  *  linking to internal hash #pci-passthrough-issues that does not exist (line 580)
     <a href="/doc/pci-devices/#pci-passthrough-issues">here</a>
- ./_site/doc/pci-devices/index.html
  *  internally linking to pci-troubleshoot, which does not exist (line 301)
     <a href="pci-troubleshoot">PCI Troubleshooting guide</a>
- ./_site/doc/pci-troubleshooting/index.html
  *  linking to internal hash #attached-devices-in-Windows-HVM-stop-working-on-suspendresume that does not exist (line 362)
     <a href="/doc/suspend-resume-troubleshooting/#attached-devices-in-Windows-HVM-stop-working-on-suspendresume">Suspend/Resume Troubleshooting</a>
htmlproofer 3.16.0 | Error:  HTML-Proofer found 3 failures!
```

2020-10-25 08:14 UTC, PROTechThor commented
@andrewdavidwong All good now :)

2020-10-25 12:11 UTC, merged