[GSoD] Nvidia Troubleshooting
QubesOS/qubes-doc pull request #1070
Opened 2020-10-30 15:30 UTC by PROTechThor

**Sources**

- https://github.com/QubesOS/qubes-issues/issues/5272
- https://www.qubes-os.org/doc/nvidia-troubleshooting/
- https://www.qubes-os.org/doc/install-nvidia-driver/

2020-11-01 03:30 UTC, marmarek requested changes
Removing "How to Remove VMs Manually" is not related to this PR.

2020-11-01 03:30 UTC, marmarek commented on external/troubleshooting/nvidia-troubleshooting.md
> +    This will temporarily disable nouveau until next boot.
Editing this file won't be temporary. It will be effective until manually edited to the original state back.

2020-11-01 07:41 UTC, PROTechThor commented
> Removing "How to Remove VMs Manually" is not related to this PR.
@marmarek I know, but it seemed a unnecessary to make a new PR for it, when I could just do it here. Would you like me to separate them?

2020-11-20 12:29 UTC, marmarek commented
@PROTechThor can you resolve merge conflict? Otherwise it should be good.

2020-11-24 18:13 UTC, marmarek approved these changes
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Approved as of 265d03feb0c4b618ab6fe3ae8bde926718d48b90
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAl+9TVoACgkQ8yiUvpaE
k4ogRQ//R3nJYGLbbi1Ge+FNMIMJFOPFNU5GNcsBw4EAEe2vHXgktipiHdRtJagm
UurPhaApu6iizCQOmzi3i5dgKpIivn562hWgvuDnjYdq21tiNApu1q+C8xtAgLyu
DKUWF7CN0/gUEM8/MkLEuLM/FlEqbxF7zk7EW2lZosh/0STZXIURo7ZaLnAAYeZC
oXEigvjGfd7+3QphhPKzZjwBGaKgSFBQJOW0Yj/Ai8XIlWGPO/wCrbaVUaasPTp2
1OYny3r7SBLXuMlSvhzdC3L/LtdX52cWSbGgUxq8/0u/Zj7OFpyfrvP+GuzdnTFO
/M6cbGHRsNF2lZt41bSeN7LIgwRYbhKCT/A6S/TlPwb04WoOlfX65o3BvXP7YLgo
Y3ZcoKlaeRaNjxUjjY7PeYqsN137vRQNN1CTF9AvY7FVlg/ds3dcNh+E2V3SOtGz
J6wAru0Ba1o4j/Jj21GBL1FlQPC0bYR4lDttyXCKBeJhTOzhiPGcbfvSWMNO9DDP
DNbSHXER8AjuMM61o9pRV3CV9/0QSAo8ZQFrorqKKPYk5ru8DayvgGNuulSo7RvJ
KRzz7XO8vhGImhpCS4ScijRnXRkbRu5GKvxJjnq1FbeZUlEmZtHIMq1LSt279bZg
BzBOJK4t50cazEosG+Z3ypS3ljXqMAaeRwTBHggEThjPPt8eHVA=
=y5yR
-----END PGP SIGNATURE-----
```

2020-11-25 12:14 UTC, merged