[GSoD] Hardware Troubleshooting
QubesOS/qubes-doc pull request #1085
Opened 2020-11-14 17:39 UTC by PROTechThor

2020-11-16 14:20 UTC, marmarek requested changes

2020-11-16 14:20 UTC, marmarek commented on user/troubleshooting/installation-troubleshooting.md
> +If the setting is not configured correctly, it means that your hardware won’t be able to leverage some Qubes security features, such as a strict isolation of the networking and USB hardware.
This is getting more strict with recent versions:
- Qubes 4.0: default installation won't function properly without IOMMU, as default sys-net and sys-usb qubes require IOMMU; it's possible to configure then to reduce isolation and not use IOMMU by changing virtualization mode of those two VMs to "PV"
- Qubes 4.1: IOMMU is strictly required, even for PV; it is not possible to use Qubes on a system without IOMMU

2020-11-18 15:55 UTC, PROTechThor commented
@marmarek All good now?

2020-11-18 16:07 UTC, marmarek approved these changes

2020-11-18 16:07 UTC, marmarek commented
PipelineRetry

2020-11-18 16:13 UTC, fepitre commented
PipelineRetry

2020-11-18 16:25 UTC, fepitre commented
PipelineRetry

2020-11-20 12:20 UTC, marmarek commented
PipelineRetry

2020-12-05 21:20 UTC, andrewdavidwong commented
I believe I'm just waiting for a signed approved from @marmarek before merging this.

2021-02-11 03:34 UTC, PROTechThor commented
@marmarek Hi. Can you please give this a final review/approval so it can be merged already? It's been months already :)

2021-02-12 02:22 UTC, marmarek approved these changes
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Approved as of 1b9b4955740cf1bc6cf738dc2d28ae1080e54101
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAmAl5lkACgkQ8yiUvpaE
k4qz2A/+JUYM8BBXrM+VFX553QWSDPb1ltOZNmGRVQxlSUxMAuLSB1eNOMTb8Hxl
DjuPAcCrmCI3z43yiB3x5h2bwq4tLRbWxn5ujiCtU8HWPsMzuCaBjUxAoi0t+ctS
8pG9yEhiFXLo5taEKdMNe2bux2NXDeQ5YvIFceTdIUDHoMFTdtUdUBXJkz/TFqZ4
yjnVR5cQhRCgFjwI+hdElXf4qebJ8mqlncf8aRZ8+BZ5KHNpPp/oMLTENU25ewMl
eo0ZO5n5/0KJwOan4qJkChV4oo/qvijoa72ta/gEPXIfCz6UTts734EEkYEXJS27
xcq9vEze9Eni9lOWAZBPPy7uA0tFbJFoIrC+J92f+dq2ZVol52r9UT9y0XInAzHx
rqce7SMa29XJA6a8o7l3NGpYbeFxZ2oFgCbVqm0R/2AXG4DCEpUhSY6+CzaHahhi
EDU8uo1SySzDzntzkdEFxQ5Y0+pTFWmQbXoX26GEH2QVr329AHEl+oOMtY8NISYv
OsXPU52p8ztVrW5AUqG0nhoRepY/jQWtHPt/aos3jk+9vGyuYRXnWqIyjtRRjQKo
FtlWYfZaXaBvlZS9+nT6WgYe7cU8X6awyPBVIoX/DbVMY31U5m7ekYH9tAYYZRdR
UkujQ7usPG7liCZThZY64ObdFXRllqO1RczYOObSZ4g/fkJLXX4=
=B/83
-----END PGP SIGNATURE-----
```

2021-02-15 12:30 UTC, merged