[GSoD] Update Troubleshooting
QubesOS/qubes-doc pull request #1092
Opened 2020-11-20 23:25 UTC by PROTechThor

I basically just moved stuff around. There's no new content. 

The "Lost internet access after a TemplateVM update" seemed to be outdated (since 2013). I wasn't sure whether to keep it or not. I added a line indicating it may not be relevant anymore.

2020-11-21 15:20 UTC, andrewdavidwong commented
`dnf` update questions are definitely very common. Even if this is mostly moving stuff around, perhaps this is a good opportunity to have Marek review the content to see if any substantive improvements can be made.

2020-11-24 18:19 UTC, marmarek requested changes

2020-11-24 18:19 UTC, marmarek commented on user/troubleshooting/update-troubleshooting.md
> +[It's a longstanding Windows bug.](https://superuser.com/questions/951960/windows-7-sp1-windows-update-stuck-checking-for-updates)
I'd note also the link contains solutions for the issue.

2020-11-24 18:19 UTC, marmarek commented on user/troubleshooting/update-troubleshooting.md
> +In your TemplateVMs, open a terminal and run `sudo dnf upgrade`.
This command applies to Fedora template only. For Debian it is `apt-get update && apt-get dist-upgrade`. You may also link to https://www.qubes-os.org/doc/software-update-domu/#updating-software-in-templatevms for details.

2020-11-24 19:13 UTC, PROTechThor commented
@marmarek All good now?

2020-11-25 02:41 UTC, marmarek approved these changes
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Approved as of 3303fab5e76d2e4efbae40039fe2a7c7673d2a61
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAl+9xF8ACgkQ8yiUvpaE
k4ogtQ/7B8/IKgBc1EXMigPvC7Lsp0FvH6kellnCOuuYR1amA86LKXTlkwwZZyrd
/7PYpHygK6aQ6Txex8UqN2gyapdSIcH/OFHKVIIRoz9OufH+EbHKz0MuTf15lVVS
ZznFWtZQ7uWO7n2nhyzairm2tXakZuBSE/xMljLxAWWhrLn5Mv+3NForoKXw+V5J
3dIdMXwj6flrlfNLeHH4MdNC+REX7euiZYM1mTVzU9yTW5tN9ByQjkbP3NYezkbe
JosKcGcoby+jHT7tJmPsmRiDNSAfe+rmIv5IjQzthRoTT+12dAZlduCV8ZCInl5u
zaZ3g06/r71iCW+YcPxCcP4/gPM0w+NfDsLG2hcGPDDWcRBtVChds1jlmpZkDdbi
46L/l6+x3DptGr70a+g1uSdzdDnMysyW5K3nCKv9IR2A4R+phsJOYr6mkmrEi1IJ
k2tFVt2GIfWV5Vfy8vuy1Ncgy6osnCCX7Vjm53hKuH5vIIUXE5n/iFMjHB6dExAi
heAVR5MZpPwnnyjW3k56BZPbGGd/4gP9ZGGoxodbv6BWOI2NvOK1Naf7CkDIhme7
3+RyaAyKXsdy/tAovLcvLAI612UNOkSZQSc98O8iVSZ9zsxlrQJNFQXIv3+NTCAF
gwKUShMTNUM32gx37+vZzzttfDRXH6lYpBYM4PXDHn23QmbOLuQ=
=Pp+J
-----END PGP SIGNATURE-----
```

2020-11-25 12:20 UTC, merged