Generalize ISO offset instructions
QubesOS/qubes-doc pull request #1122
Opened 2021-03-11 05:37 UTC by andrewdavidwong

This is a user-requested change.

2021-03-13 15:30 UTC, marmarek requested changes

2021-03-13 15:30 UTC, marmarek commented on user/troubleshooting/uefi-troubleshooting.md
> +03. Using the start address and the size of the EFI partition, setup a loop device for it. This depends on the offset you found in the previous step and is specific to your ISO. Here is an example co
In fact, it should be much simpler to just use `losetup -P` and let the kernel parse the partition table. This way, you'll get `/dev/loop0p2` with the EFI partition. No need to manually entering any offsets.

2021-03-15 04:39 UTC, andrewdavidwong commented
I don't understand why the CI check failed. I'll retry it.

2021-03-15 12:15 UTC, marmarek requested changes

2021-03-15 12:15 UTC, marmarek commented on user/troubleshooting/uefi-troubleshooting.md
> +01. Get EFI partition boundaries (replacing `X` with your ISO's version name): `parted Qubes-RX-x86_64.iso unit B print`
This step is unnecessary in the new version.

2021-03-15 12:15 UTC, marmarek commented on user/troubleshooting/uefi-troubleshooting.md
> +03. Mount the loop device: `sudo mount /dev/loop0 /mnt`
```suggestion
03. Mount the loop device: `sudo mount /dev/loop0p2 /mnt`
```

2021-03-15 22:20 UTC, marmarek approved these changes
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Approved as of fcc3f650d565f3a6aa79aa593df175854a62039e
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAmBP3Z8ACgkQ8yiUvpaE
k4qjMw/+MQ4rW5WFROMnz+6/VovbcDZz6X5cNFDIwbJGLg064bRUDhNnr2w2If/J
SBmV3TOtzwNgt6FajCOaHSvhsFaR2O/jlOUu6OGPycd0ZbzgjtpXP9Ri9CtF9MIJ
amHqfxYs5CxSDPy8tn/b5p9CIXiddZujpxZVPcW+5UPGu7WNSvQamLlKXjEfh1hS
V1/LXPDKBNsGEp80nCuVmGcxn2U6+h/arMQLCzb7m6aFUjHX855sQCAONHET2bsQ
paqah7VIgGm9XJJmXu4BHSBOuI48NMxih1bX4bM1iLwwUjXCEVjmcUJcw7OBNQ89
5AwjTjcIKRiuP3b6UTrZBTxOxTIfKZuoLM5EDDY/SLd++IsWcRdhJBnUzMY4ljCc
BoZuaKNB3y9JVdk/F/krmien5Ed7yO7t0zgioXgr0ZUxXLad4gtVo2YqBT9gpy+r
ASWIsnGGcfIw+Bbhqc8IqmsWNeMw4NTWu8OG48sGq7VECehYenCba3DJssQmUyg4
9SBfWEBwgKS4ySdxC4kM8P/C0laF+N3TwZ0Hmz2a9ONhZmXBVEjBxLK0ul55O8pH
5FUDl7YsiLagT6fZooIazWyvz1WQ0Zs7Bx1suHUZ2UyBqBDSJMPWTUzhj7GmlxgR
ZwWpwBozoK9mMgCZy4X1FiwbqTpGEUNzXXCuG85M9xmuYUfvGtY=
=/QSr
-----END PGP SIGNATURE-----
```

2021-03-15 22:30 UTC, merged