test-bench: section on installing testing deps
QubesOS/qubes-doc pull request #1176
Opened 2021-07-15 10:34 UTC by deeplow

2021-07-16 20:42 UTC, andrewdavidwong requested changes
Generally, the names of things should be written the same way they appear in their respective doc pages or their official names outside of Qubes, e.g., `Split GPG`, `Salt`, and `SaltStack`. Please avoid this all-lowercase-with-no-spaces naming (unless that's actually how the thing is named).

2021-07-17 10:38 UTC, unman reviewed
You should fix the numerous other spelling/grammar errors on this page at the same time.

2021-07-17 10:39 UTC, unman commented on developer/debugging/test-bench.md
> +   # install them same configuration as the one in OpenQA
**the same**

2021-07-17 15:09 UTC, deeplow commented on developer/debugging/test-bench.md
> +   # install them same configuration as the one in OpenQA
thanks for catching it

2021-07-17 15:09 UTC, deeplow commented
> Generally, the names of things should be written the same way they appear in their respective doc pages or their official names outside of Qubes, e.g., `Split GPG`, `Salt`, and `SaltStack`. Please avoid this all-lowercase-with-no-spaces naming (unless that's actually how the thing is named).

Done.

2021-07-19 01:50 UTC, andrewdavidwong approved these changes

2021-07-19 01:52 UTC, andrewdavidwong commented
Actually, @unman, would you be willing to review this so we can give Marek a break?

2021-07-19 13:09 UTC, unman commented
On Sun, Jul 18, 2021 at 06:52:12PM -0700, Andrew David Wong wrote:
> Actually, @unman, would you be willing to review this so we can give Marek a break?
> 

Yes, tomorrow.

2021-08-04 11:33 UTC, marmarek requested changes
Besides one minor note, looks good.

2021-08-04 11:33 UTC, marmarek commented on developer/debugging/test-bench.md
> +   sudo systemctl restart qubesd
qubesd restart is not needed after just adding salt recipes.

2021-08-05 05:30 UTC, andrewdavidwong commented
Ok, looks like @marmarek will be reviewing this instead of @unman after all.

> Besides one minor note, looks good.

Shall I wait for your usual signed approval comment, per our [policy](https://www.qubes-os.org/doc/how-to-edit-the-documentation/#security)?

2021-10-01 14:37 UTC, merged