Add GRUB installation steps to managing-vm-kernels.md
QubesOS/qubes-doc pull request #1189
Opened 2021-08-15 20:32 UTC by SaswatPadhi

Resolves QubesOS/qubes-issues#6178

Added GRUB installation steps:
- `grub2-install` on Fedora
- `grub-install` on Debian

2021-08-16 03:45 UTC, andrewdavidwong requested changes

2021-08-16 03:45 UTC, andrewdavidwong commented on user/advanced-topics/managing-vm-kernels.md
> +~~~
If I'm reading this correctly, this repeats the command that you instructed the user to run above. Won't that be confusing? Also, should we really be telling the user the run this command above, at the start, when we later mention the GUI option?

2021-08-16 03:47 UTC, andrewdavidwong commented
Never mind. I was looking at a collapsed diff. Deleting my erroneous comments.

2021-08-21 05:03 UTC, SaswatPadhi commented
@marmarek, please take a look when you get a chance. Fairly small change, and I've tested the proposed change on multiple TemplateVMs.

2022-02-10 13:54 UTC, marmarek approved these changes
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Approved as of f4c00061dd0cec5d596e1c7e815e26008105d5d3
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAmIFGQgACgkQ8yiUvpaE
k4pdwxAA0nQ7y+rmflgfM1QbxHIComUmMs+zhoBIXpKgnBZYKjIjQV9RrQLljoYd
FI2n5CSkhSQkHh6Tpf0HwtqTUBDr+tZeIOtvD4ZCYVQwxepb+vrC4e7To88HXQiS
D3/QbaLS/gGm8L+8dZ2142ls3mdy+NFjUPLtUUXVq0auj3+rVDFFBRt9HSnM6jFf
8CREmKNvRt1IiIYFPwI15skGYBIu/LeuYU9/AK1N77aprrgET7nF18yuB8Xvllnw
lUCTX6+niggEOL7cg4KTy12fSrxt33k+trjsjkU11EUKwOWCEP03x2EjlhN5SHjR
0oFC7Y2tB2MaOEK8s8ypgkr5k6akYek5Vw41j5kytzCrSAQjm5zlHnx8lKI3zjVs
NpmxXhRKDah3QfUHlpKm7tRfzO3dFYkxZKFrFE8a97I/15r9gJrQE9S7A04aTCi+
jV3GCjmhfyYnIqp4CAfAktCkFf92qTvU12D7Ruk+52k15LbZavrNqNl6JyEjH5mt
GXMPWN9jlzUFsDMnNycnxefgZNPkt9wO4nu+/6UBW01R8s/eCcFnsZrSHWIFuNbn
i5ozezehh46b057mVC/4sXbrl6QsxiBTZnMHDWpejF+Ne5x9+Gig32+IDeK8iFMj
RxKBxQ0BG/6YcgAkVnigyy9vjArqduWirUW3N7/z3ytiAlcxNKw=
=WZV/
-----END PGP SIGNATURE-----
```

2022-02-11 02:34 UTC, merged