Replace all refs to template operations with qubes-dom0-update with qvm-template
QubesOS/qubes-doc pull request #1328
Opened 2023-06-07 14:34 UTC by unman

As title
Consistent treatment of the GUI tool and references to it is needed.

2023-06-16 01:21 UTC, rapenne-s requested changes
mostly nitpicking about qvm-template usage consistency

2023-06-16 01:21 UTC, rapenne-s commented on user/how-to-guides/how-to-reinstall-a-template.md
>  4. Reinstall the target template in dom0:
```suggestion
4. Reinstall the target template:
```
I'm not aware templates can be installed outside dom0, this adds confusion

2023-06-16 01:21 UTC, rapenne-s commented on user/how-to-guides/how-to-reinstall-a-template.md
> +    $ qvm-template  --enablerepo=<optional-additional-repo> \
```suggestion
    $ qvm-template  --enablerepo=<optional-additional-repo> install \
```

the subcommand is missing

2023-06-16 01:21 UTC, rapenne-s commented on user/how-to-guides/how-to-reinstall-a-template.md
> +    $ qvm-template install --enablerepo=qubes-templates-community \
```suggestion
    $ qvm-template --enablerepo=qubes-templates-community install \
```
the document should stay consistent, the subcommand is given after the parameters, and this matches the command's synopsis in the man page https://dev.qubes-os.org/projects/core-admin-client/en/latest/manpages/qvm-template.html#synopsis

2023-06-16 01:21 UTC, rapenne-s commented on user/templates/debian/debian.md
> +$ qvm-template debian-XX
```suggestion
$ qvm-template install debian-XX
```
missing subcommand

2023-06-16 01:21 UTC, rapenne-s commented on user/templates/debian/debian.md
> +[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-itl debian-10-minimal
```suggestion
[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-itl install debian-10-minimal
```
missing subcommand

2023-06-16 01:21 UTC, rapenne-s commented on user/templates/debian/debian.md
> +[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-itl debian-10
```suggestion
[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-itl install debian-10
```
missng subcommand

2023-06-16 01:21 UTC, rapenne-s commented on user/templates/minimal-templates.md
> +[user@dom0 ~]$ qvm-template <DISTRO_NAME>-<RELEASE_NUMBER>-minimal
```suggestion
[user@dom0 ~]$ qvm-template install <DISTRO_NAME>-<RELEASE_NUMBER>-minimal
```

2023-06-16 01:21 UTC, rapenne-s commented on user/templates/minimal-templates.md
> +[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-itl-testing <DISTRO_NAME>-<RELEASE_NUMBER>-minimal
```suggestion
[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-itl-testing install <DISTRO_NAME>-<RELEASE_NUMBER>-minimal
```

2023-06-16 01:21 UTC, rapenne-s commented on user/templates/minimal-templates.md
> +[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-community <DISTRO_NAME>-<RELEASE_NUMBER>-minimal
```suggestion
[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-community install <DISTRO_NAME>-<RELEASE_NUMBER>-minimal
```

2023-06-16 01:21 UTC, rapenne-s commented on user/templates/xfce-templates.md
> +[user@dom0 ~]$ qvm-template install --enablerepo=qubes-templates-itl-testing X-xfce
```suggestion
[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-itl-testing install X-xfce
```
consistency

2023-06-16 01:21 UTC, rapenne-s commented on user/templates/xfce-templates.md
> +[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-community X-xfce
```suggestion
[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-community install X-xfce
```

2023-06-16 01:21 UTC, rapenne-s commented on user/templates/xfce-templates.md
> +[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-community-testing X-xfce
```suggestion
[user@dom0 ~]$ qvm-template --enablerepo=qubes-templates-community-testing install X-xfce
```

2023-06-16 01:21 UTC, rapenne-s commented on user/how-to-guides/how-to-reinstall-a-template.md
> +Replace `qubes-template-name` with the name of the template you wish to reinstall.
```suggestion
Replace `qubes-template-name` with the name of the template you wish to reinstall.
A list of available templates can be obtained using the command `qvm-template list`.
```

2023-06-30 15:18 UTC, rapenne-s commented
It's curious the CI reports an error on an unknown word that is already in the documentation, and that it will be ignored once it's committed...

https://gitlab.com/QubesOS/qubes-doc/-/jobs/4430914533#L458

2023-07-01 02:00 UTC, andrewdavidwong commented
> It's curious the CI reports an error on an unknown word that is already in the documentation, and that it will be ignored once it's committed...
> 
> https://gitlab.com/QubesOS/qubes-doc/-/jobs/4430914533#L458

Is it because it's case-sensitive (i.e., `repo` is already on the allow list, but `Repo` isn't)? If not, then I have no idea why it would do that.

2023-07-01 02:06 UTC, unman commented
On Fri, Jun 30, 2023 at 07:01:01PM -0700, Andrew David Wong wrote:
> > It's curious the CI reports an error on an unknown word that is already in the documentation, and that it will be ignored once it's committed...
> > 
> > https://gitlab.com/QubesOS/qubes-doc/-/jobs/4430914533#L458
> 
> Is it because it's case-sensitive (i.e., `repo` is already on the allow list, but `Repo` isn't)? If not, then I have no idea why it would do that.
> 
This is the reason here.

2024-02-07 13:30 UTC, closed without merging