Update recommendations and notes regarding microcode and AMD
QubesOS/qubes-doc pull request #1424
Opened 2024-09-02 16:01 UTC by andrewdavidwong

Based on discussion with @DemiMarie

CC: @marmarek

2024-09-02 19:09 UTC, marmarek commented on user/hardware/system-requirements.md
> +    receiving microcode updates (see [below](#important-updates) for details).
Maybe worth linking somewhere to the list of support end dates for Intel? https://www.intel.com/content/www/us/en/support/articles/000022396/processors.html (those missing don't have announced date yet, and there is no clear policy how long each CPU family is supported...)

2024-09-03 06:37 UTC, fepitre commented on user/hardware/system-requirements.md
> +  lifted, but it did not make fixes  available for client platforms facing the
double spaces after "fixes"

2024-09-04 01:18 UTC, DemiMarie commented
Pinging @andyhhp

2024-09-04 02:02 UTC, DemiMarie commented on user/hardware/system-requirements.md
> +  while some others take a very long time to complete it.
```suggestion
  Historically, AMD has sometimes been slow to complete step (1), at least for its
  client (as opposed to server) platforms. In some cases
  (notably Speculative Return Stack Overflow, XSA-434/QSB-093),
  AMD has made fixes available for its server platforms very shortly
  after a security embargo was lifted, but it did not make fixes available
  for client platforms facing the same vulnerability until weeks or
  months later. (A "security embargo" is the practice of avoiding public
  disclosure of a security vulnerability prior to a
  designated date.) By contrast, Intel has consistently made fixes available for
  new CPU vulnerabilities across its supported platforms very shortly after
  security embargoes have been lifted.

  Step (2) varies by vendor. Many vendors fail to complete step (2) at all,
  while some others take a very long time to complete it.
```

2024-09-04 02:07 UTC, DemiMarie requested changes
This should not be merged until some fact checks have completed.

2024-09-15 01:41 UTC, DemiMarie approved these changes

2024-09-15 17:14 UTC, merged